name: Deploy Main Branch

on:
  pull_request:
    branches:
      - main
      - master
    types: [closed]

jobs:
  build-and-deploy-staging:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v2

      - name: set ENV
        uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy Stack
        run: yarn cdk deploy --require-approval never
        if: success() || failure()

      - name: Run Integration Test
        run: yarn test:int --stack=eventnet-test-stack --region=eu-west-2  --runInBand --all --runInBand
        if: success() || failure()
